export default () => ({
  paymentReceiveList: [],
  currentStep: 1,
  selectedPaymentReceive: [],
  summaryData: [],
  latitude: null,
  longitude: null,
  receiveCash: 0,
  receiveCheck: 0,
  receiveTransfer: 0,
  receiveCreditcard: 0,
  receiveCashBank: null,
  receiveTransferBank: null,
  receiveCheckBank: null,
  cashFiles:[],
  checkFiles:[],
  transferFiles:[],
  creditCardFiles: [],
  checkdate: "",
  checkno: "",
});
